import colors from '../../style/colors';
import { darken, rgba } from '../../style';

export default {
	sizes: {
		auto: {
			padding: 0,
			height: 'auto',
			fontSize: '16px',
		},
		xs: {
			padding: '6px 16px',
			height: '24px',
			fontSize: '12px',
			loaderProps: { size: 'xxs' },
		},
		sm: {
			padding: '6px 16px',
			height: '32px',
			fontSize: '14px',
			loaderProps: { size: 'xxs' },
		},
		md: {
			padding: '8px 10px',
			height: '40px',
			fontSize: '16px',
			loaderProps: { size: 'xs' },
		},
		lg: {
			padding: '6px 16px',
			height: '48px',
			fontSize: '16px',
			loaderProps: { size: 'xs' },
		},
		xl: {
			padding: '6px 16px',
			height: '56px',
			fontSize: '16px',
			loaderProps: { size: 'sm' },
		},
		xxl: {
			padding: '6px 16px',
			height: '64px',
			fontSize: '16px',
			loaderProps: { size: 'sm' },
		},
	},

	variants: {
		action: {
			bgColor: 'action',
			color: colors.white,
			loaderProps: { variant: 'white' },
			disabledColor: colors.gray50,
		},
		secondary: {
			bgColor: colors.gray95,
			activeBgColor: 'actionLight',
			activeColor: 'action',
			borderColor: colors.gray95,
			hoverBorderColor: colors.gray90,
			activeBorderColor: 'actionLight',
			hoverBgColor: colors.gray90,
			color: colors.blackish,
			loaderProps: { variant: 'white' },
		},
		'secondary-dark': {
			bgColor: colors.gray90,
			activeBgColor: 'actionLight',
			activeColor: 'action',
			borderColor: colors.gray95,
			hoverBorderColor: colors.gray80,
			activeBorderColor: 'actionLight',
			hoverBgColor: colors.gray80,
			color: colors.blackish,
			loaderProps: { variant: 'white' },
		},
		'secondary-clean': {
			bgColor: colors.transparent,
			activeBgColor: 'actionLight',
			activeBorderColor: 'actionLight',
			activeColor: 'action',
			borderColor: colors.transparent,
			hoverBgColor: colors.gray90,
			color: colors.blackish,
			disabledColor: colors.gray50,
			loaderProps: { variant: 'white' },
		},
		tertiary: {
			bgColor: colors.transparent,
			activeBgColor: colors.transparent,
			activeColor: 'action',
			hoverColor: 'actionColorDarker',
			hoverBgColor: colors.transparent,
			color: 'action',
			loaderProps: { variant: 'white' },
		},
		'action-yellow-gray': {
			bgColor: colors.transparent,
			color: colors.gray50,
			hoverBgColor: colors.gray90,
			hoverBorderColor: 'transparent',
			activeBorderColor: 'transparent',
			activeBgColor: colors.yellowLight,
			activeColor: colors.gold,
		},
		'clean-gray-50': {
			bgColor: colors.transparent,
			color: colors.white,
			hoverBgColor: rgba(colors.blackish, 0.12),
			hoverBorderColor: colors.transparent,
			activeBorderColor: colors.transparent,
			activeBgColor: rgba(colors.blackish, 0.24),
			disabledBackground: colors.transparent,
			disabledColor: colors.white,
		},
		'transparent-gray-80': {
			color: colors.gray50,
			bgColor: colors.transparent,
			borderColor: colors.gray80,
			hoverBgColor: rgba(colors.gray80, 0.12),
			hoverBorderColor: colors.transparent,
			activeBgColor: 'actionLight',
			activeBorderColor: 'actionLight',
			activeColor: 'action',
			disabledColor: colors.gray80,
		},
		'white-action': {
			bgColor: colors.white,
			borderColor: rgba(0, 0, 0, 0),
			hoverBorderColor: rgba(0, 0, 0, 0),
			activeBorderColor: rgba(0, 0, 0, 0),
			color: 'action',
			hoverBgColor: colors.gray90,
			activeBgColor: colors.gray80,
			disabledBackground: colors.white,
			disabledColor: 'action',
			loaderProps: { variant: 'action' },
		},
		'clean-gray-95-basic': {
			bgColor: colors.transparent,
			activeBgColor: darken(0.08, colors.gray95),
			hoverBgColor: colors.gray95,
			hoverColor: 'action',
			color: colors.blackish,
		},
		'opacity-black': {
			bgColor: rgba(0, 0, 0, 0.5),
			borderColor: rgba(0, 0, 0, 0),
			hoverBorderColor: rgba(0, 0, 0, 0),
			activeBorderColor: rgba(0, 0, 0, 0),
			color: colors.white,
			hoverBgColor: rgba(0, 0, 0, 0.7),
			activeBgColor: rgba(0, 0, 0, 1),
		},

		linkedin: {
			bgColor: colors.linkedin,
			color: colors.white,
			hoverBgColor: '#00628C',
			activeBgColor: '#005478',
		},
		clean: {
			bgColor: colors.transparent,
			color: 'inherit',
		},
	},
};
